### PR TITLE
Updated arctic fox textures

### PR DESCRIPTION
**Pull request by Zeracronius**
billede

### CODE REVIEW

**Comment by Zeracronius** [comment]
I don't know if the male tail has a slightly wrong offset

**Comment by Zeracronius** [comment]
Needs to reconsider texture backwards compatibility.

**Comment by Zeracronius** [comment]
Nvm, Lelo already handled this with creating a copy of parts textures under Legacy.

**Comment by Tachyonite** [comment]
It's close enough but could do slight tweaks to tail positioning

**Pull request merged**
