### PR TITLE
Updated Combat Extended Patches

### PR DESCRIPTION
**Pull request by GrahammerTek**

### CODE REVIEW

**Comment by Zeracronius** [comment]
If you move the entire thing under /1.4/Mods/CombatEvolved/ then we can use conditionally loaded folders to load it all instead.
Currently it is placed in root folder and will be loaded for all game versions including prior versions.

With conditionally loaded folders you don't need to use FindMod operation in all the patches as they will only ever be applied in the first place if the mod exist.
Defined in /LoadFolders.xml
(Mind FindMod uses display name and LoadFolders uses packagid)

**Comment by GrahammerTek** [comment]
Thanks, I never knew LoadFolders existed.

**Comment by Zeracronius** [comment]
I recently updated Giddy up patch similarly, and you can reference the changes I made here:
https://github.com/Tachyonite/Pawnmorpher/pull/801

I copied the original patch under 1.0, 1.1, 1.2 and 1.3 and then added the new support only under 1.4, while deleting everything in root.
That way we can ensure that only the relevant versions load for a given version.
In this case though, I'm not sure how much use the existing thing would be in previous rimworld versions as is.

**Comment by GrahammerTek** [comment]
Alright, it should be finished. Sorry about those last few commits, I must have had a bad morning.

**Review by Zeracronius — APPROVED** [review]
Looks fine to me, though granted i don't know enough about CE to do a thorough review.

Using "<success>always</success>" may or may not cause issues.
For smaller integrations that aren't "important" that all parts got correctly applied it's fine, but in this case, what if part of it wasn't applied and you get no errors or indicators about it?

**Comment by GrahammerTek** [comment]
I think I use "always" out of habit since I'm so used to seeing it everywhere in older patches. I did check with it set to "normal" and had no issues on my end, though.

**Pull request merged**
